name: conceptual model site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the conceptual model/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/conceptual -v ${{ github.workspace }}/_site:/srv/conceptual/_site \
        conceptuall/builder:latest /bin/bash -c "chmod 777 /srv/conceptual && conceptual build --future"
